server:
  port: 9000



spring:
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/soul?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Dirver

management:
  health:
    defaults:
      enabled: false
soul :
  sync:
    websocket :
      urls: ws://localhost:9095/websocket  //设置成你的soul-admin地址