#spring:
#  application:
#    name: coach-soul-gateway
#  main:
#    allow-bean-definition-overriding: true
##  datasource:
##    url: jdbc:mysql://localhost:3306/soul?useUnicode=true&characterEncoding=utf-8
##    username: root
##    password: 123456
##    driver-class-name: com.mysql.jdbc.Dirver
#
#server:
#  port: 9000
#
#
#coach-soul-gateway:
#  ribbon.NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://admin:admin@192.168.0.9:8761/eureka/
#    enabled: true
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#
#management:
#  health:
#    defaults:
#      enabled: false
#soul :
#  client:
#    registerType: http #zookeeper #etcd #nacos #consul
#    serverLists: http://localhost:9095 #localhost:2181 #http://localhost:2379 #localhost:8848
#    props:
#      contextPath: /springcloud
#      port: 8884
#      nacosNameSpace: SoulRegisterCenter
#  sync:
#    websocket :
#      urls: ws://localhost:9095/websocket  #设置成你的soul-admin地址
#  httpclient:
#    read-timeout: 10000
#    write-timeout: 10000
#    connect-timeout: 10000
#
#
#
#
#logging:
#  level:
#    root: info
#    org.dromara.soul: debug