spring:
  application:
    name: coach-business-server
  zipkin:
    base-url: http://192.168.0.30:9411/

server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true