spring:
  application:
    name: coach-business-server

server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true