spring:
   datasource:
     username: root
     password: 123456
     url: jdbc:mysql://127.0.0.1:3306/test_springbatch?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
     driver-class-name: com.mysql.cj.jdbc.Driver
     # 初始化数据库，文件在依赖jar包中
     schema: classpath:org/springframework/batch/core/schema-mysql.sql
     initialization-mode: always