spring:
  application:
    name: coach-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  redisson:
    host: true
    master-name: false
    cluster:
      nodes: false
  cloud:
    gateway:
      routes:
        - id: url-proxy-1
          uri: https://blog.csdn.net
          predicates:
            - Path=/csdn
        - id: coach-user-server
          uri: lb://coach-user-server
          predicates:
            - Path=/api-user/**
          filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1500000
              redis-rate-limiter.burstCapacity: 2000000
              key-resolver: "#{@remoteUrlPathKeyResolver}"
          - TokenDecoderFilter
          - StripPrefix=1
        - id: coach-business-server
          uri: lb://coach-business-server
          predicates:
            - Path=/api-business/**
          filters:
              - StripPrefix=1
        - id: coach-pay-server
          uri: lb://coach-pay-server
          predicates:
            - Path=/api-pay/**
          filters:
            - StripPrefix=1

server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@192.168.0.9:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true


