server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: url-proxy-1
          uri: https://blog.csdn.net
          predicates:
            - Path=/csdn
        - id: url-proxy-2
          uri: https://www.baidu.com
          predicates:
            - Path=/baidu