spring:
  application:
    name: coach-user-server  #应用名称，也是服务注册的名称

server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@192.168.0.9:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true