spring:
  application:
    name: coach-pay-server
  redis:
    host: 127.0.0.1
    port: 6379
    password:

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true