server:
  port: 8082

spring:
  application:
    name: coach-pay-server
  redis:
    host: 127.0.0.1
    port: 6379
    password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/