spring:
  datasource:
    # ???? url?user?password? type????
    # type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/coach_example?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    # ?????url??????
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # druid?????? ????????????
    druid:
      # ?????????????
      initial-size: 1 #?????????????????0???????????init????????getConnection?
      min-idle: 1
      max-active: 20
      # ????????????? ????
      max-wait: 60000
      # ???????????????????????????????
      time-between-eviction-runsMillis: 2000
      # ??????????????????????
      min-evictable-idle-timeMillis: 600000
      # ??????????????????????
      max-evictable-idle-timeMillis: 900000
      # ?????????sql???validationQuery?null?testOnBorrow?testOnReturn?testWhileIdle??????
      validation-query: select 1
      # ??????????????????
      validation-query-timeout: 10
      # ???????validationQuery????????????????????
      test-on-borrow: false
      # ???????validationQuery????????????????????
      test-on-return: false
      # ????true?????????????????????????timeBetweenEvictionRunsMillis???validationQuery????????
      test-while-idle: true
      # ?????minIdle??????????????minEvictableIdleTimeMillis?????keepAlive??
      keep-alive: true
      # ????preparedStatement????PSCache
      pool-prepared-statements: true
      max-open-prepared-statements: 20 #???????
      # ???PSCache???????0????0??poolPreparedStatements???????true
      max-pool-prepared-statement-per-connection-size: 20
      # ?????????filters???????????
      filters: stat,wall
      # ??connectProperties?????mergeSql????SQL????
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # ??????DruidDataSource?????
      use-global-data-source-stat: true