spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/praxis_example?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    druid:
      # 主数据源
      user:
        driver-class-name: com.mysql.jdbc.Driver
        # 默认数据库连接（配置库）
        url: jdbc:mysql://127.0.0.1:3306/coach_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      order:
        driver-class-name: com.mysql.jdbc.Driver
        # 默认数据库连接（配置库）
        url: jdbc:mysql://127.0.0.1:3306/coach_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      business:
        driver-class-name: com.mysql.jdbc.Driver
        # 默认数据库连接（配置库）
        url: jdbc:mysql://127.0.0.1:3306/coach_business?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
logging:
  level:
    root: debug
    com:
      evol:
        mapper= debug
mybatis:
  mapper-locations: classpath*:mapper/*.xml
